# Generated by Django 5.2.16 on 2026-08-01 17:54

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text="'#tariffs' або '/terms-and-safety/'", max_length=300)),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('placement', models.CharField(choices=[('navbar', 'Navbar'), ('footer', 'Footer (Legal)')], default='navbar', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('cms/page_home.html', 'Головна'), ('cms/page_standard.html', 'Стандартна сторінка'), ('catalog/location.html', 'Лендінг локації (Етап 4)')], default='cms/page_standard.html', max_length=60)),
                ('is_homepage', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сторінка',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Відгук',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TUYYO.CLUB', max_length=60, verbose_name='Назва сайту')),
                ('copyright', models.CharField(default='© 2026 TUYYO GROUP S.L.', max_length=120)),
                ('company_legal_name', models.CharField(default='TUYYO GROUP S.L.', max_length=120)),
                ('cif', models.CharField(default='B-03918234', max_length=30, verbose_name='CIF / NIF')),
                ('licencia', models.CharField(default='VA-TUR-2024/9182', max_length=60, verbose_name='Туристична ліцензія')),
                ('seguro_rc', models.CharField(default='AXA № 78192834-RC (€600,000)', max_length=120, verbose_name='Страховка RC')),
                ('phone', models.CharField(default='+34 623 575 015', max_length=30)),
                ('whatsapp_number', models.CharField(default='34623575015', max_length=20)),
                ('bizum_phone', models.CharField(default='+34 623 575 015', max_length=30)),
                ('email', models.EmailField(default='tuyyogroup@gmail.com', max_length=254)),
                ('address', models.CharField(default='Av. Miguel Hernández 25, Finestrat', max_length=200)),
                ('maps_url', models.URLField(blank=True)),
                ('google_maps_reviews_url', models.URLField(blank=True)),
                ('deposit_amount', models.PositiveIntegerField(default=150)),
                ('delivery_fee', models.PositiveIntegerField(default=20)),
                ('hero_video_url', models.URLField(blank=True)),
                ('locations', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('features_banner', 'Features-банер'), ('tariffs', 'Тарифи'), ('gallery', 'Галерея'), ('fleet', 'Флот'), ('guide_cards', 'Guide-картки'), ('locations', 'Локації'), ('reviews', 'Відгуки'), ('faq', 'FAQ'), ('cta_banner', 'CTA-банер'), ('richtext', 'Rich text'), ('location_hero', 'Hero локації'), ('paddle_guide', 'Paddle-гайд'), ('other_locations', 'Інші локації')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('anchor_id', models.SlugField(blank=True, help_text='Якір для навігації, напр. tariffs', max_length=60)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Скалярні налаштування типу')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page')),
            ],
            options={
                'verbose_name': 'Секція',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Назва іконки з icons.py', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='sections/')),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.section')),
            ],
            options={
                'verbose_name': 'Елемент секції',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SectionItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=220)),
                ('text', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=120)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.sectionitem')),
            ],
            options={
                'verbose_name': 'Елемент секції Translation',
                'db_table': 'cms_sectionitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('eyebrow', models.CharField(blank=True, max_length=160)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, help_text='HTML для richtext-секцій')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.section')),
            ],
            options={
                'verbose_name': 'Секція Translation',
                'db_table': 'cms_section_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('footer_description', models.TextField(blank=True)),
                ('default_meta_title', models.CharField(blank=True, max_length=200)),
                ('default_meta_description', models.CharField(blank=True, max_length=320)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.sitesettings')),
            ],
            options={
                'verbose_name': 'Налаштування сайту Translation',
                'db_table': 'cms_sitesettings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuLinkTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(max_length=120)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.menulink')),
            ],
            options={
                'verbose_name': 'Пункт меню Translation',
                'db_table': 'cms_menulink_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='cms_menulink_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.page')),
            ],
            options={
                'verbose_name': 'Сторінка Translation',
                'db_table': 'cms_page_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='cms_page_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReviewTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.TextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.review')),
            ],
            options={
                'verbose_name': 'Відгук Translation',
                'db_table': 'cms_review_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='cms_review_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='uniq_section_page_order'),
        ),
        migrations.AddConstraint(
            model_name='sectionitemtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='cms_sectionitem_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='sectiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='cms_section_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='sitesettingstranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='cms_sitesettings_translation_uniq_lang'),
        ),
    ]
